name             'elasticsearch'
maintainer       'Atsushi Nakajyo'
maintainer_email 'jyotti@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures elasticsearch'
long_description 'Installs/Configures elasticsearch'
version          '0.1.0'

depends 'yum', '~> 3.3'
depends 'java', '~> 1.28'
